### ISSUE TITLE
verify: False but still `x509: certificate signed by unknown authority`

### ISSUE THREAD

**Issue by kiblik** [openstack-exporter/openstack-exporter#32]
I tried to disable cert verification but exporter still returns `x509: certificate signed by unknown authority`

config:
```yaml
clouds:
 default:
   auth:
     username: xxx
     password: yyy
     project_name: zzz
     verify: False
     auth_url: https://XXX:5000/v2.0
```
Run:
```bash
# docker run -v /opt/os_exporter/:/etc/openstack/ -it quay.io/niedbalski/openstack-exporter-linux-amd64:master default
INFO[0000] Starting openstack exporter version (version=, branch=, revision=) for cloud: default  source="main.go:38"
INFO[0000] Build context (go=go1.11.13, user=, date=)    source="main.go:39"
ERRO[0000] enabling exporter for service network failed: Post https://XXX:5000/v2.0/tokens: x509: certificate signed by unknown authority  source="main.go:51"
ERRO[0000] enabling exporter for service compute failed: Post https://XXX:5000/v2.0/tokens: x509: certificate signed by unknown authority  source="main.go:51"
ERRO[0000] enabling exporter for service image failed: Post https:///XXX:5000/v2.0/tokens: x509: certificate signed by unknown authority  source="main.go:51"
ERRO[0000] enabling exporter for service volume failed: Post https://XXX:5000/v2.0/tokens: x509: certificate signed by unknown authority  source="main.go:51"
ERRO[0000] enabling exporter for service identity failed: Post https://XXX:5000/v2.0/tokens: x509: certificate signed by unknown authority  source="main.go:51"
INFO[0000] Starting HTTP server on :9180                 source="main.go:72"
```

**Comment by niedbalski** [comment]
Hello @kiblik 

Unfortunately, this is a regression introduced by the switch to the gophercloud library. The verify option goes one level up in the configuration YAML (Check README.md), I have fixed it on the code
to pass a new transport to the HTTP client that ignores the SSL verification.

This has to be fixed in the gophercloud library, by the time being, the code #33 should make
this work.

Please let me know if the current master image works for you.

Thanks.

**Comment by kiblik** [comment]
Hi @niedbalski,

You moved verify option one and half level up :smile: because you have _wrong indentation_ there
```bash
$ cat example.yaml 
clouds:
 default:
   region_name: {{ openstack_region_name }}
   identity_api_version: 3
   identity_interface: internal
   auth:
     username: {{ keystone_admin_user }}
     password: {{ keystone_admin_password }}
     project_name: {{ keystone_admin_project }}
     project_domain_name: 'Default'
     user_domain_name: 'Default'
     auth_url: {{ admin_protocol }}://{{ kolla_internal_fqdn }}:{{ keystone_admin_port }}/v3
     cacert: |
            ---- BEGIN CERTIFICATE ---
      ...
  verify: true | false  // disable || enable SSL certificate verification
$ yamllint example.yaml | grep indentation
  3:4       error    wrong indentation: expected 2 but found 3  (indentation)
  7:6       error    wrong indentation: expected 4 but found 5  (indentation)
  15:7      error    wrong indentation: expected 5 but found 6  (indentation)
  16:3      error    wrong indentation: expected 1 but found 2  (indentation)
```

I tried one level
```bash
# docker pull quay.io/niedbalski/openstack-exporter-linux-amd64:master
...
# cat clouds.yaml 
clouds:
  default:
    auth:
      username: xxx
      ...
    verify: False
# docker run -v /opt/os_exporter/:/etc/openstack/ -it quay.io/niedbalski/openstack-exporter-linux-amd64:master default
INFO[0000] Starting openstack exporter version (version=, branch=, revision=) for cloud: default  source="main.go:38"
INFO[0000] Build context (go=go1.11.13, user=, date=)    source="main.go:39"
ERRO[0000] enabling exporter for service image failed: Post https://XXX:5000/v2.0/tokens: x509: certificate signed by unknown authority  source="main.go:51"
ERRO[0000] enabling exporter for service volume failed: Post https://XXX:5000/v2.0/tokens: x509: certificate signed by unknown authority  source="main.go:51"
ERRO[0000] enabling exporter for service identity failed: Post https://XXX:5000/v2.0/tokens: x509: certificate signed by unknown authority  source="main.go:51"
ERRO[0000] enabling exporter for service network failed: Post https://XXX:5000/v2.0/tokens: x509: certificate signed by unknown authority  source="main.go:51"
ERRO[0000] enabling exporter for service compute failed: Post https://XXX:5000/v2.0/tokens: x509: certificate signed by unknown authority  source="main.go:51"
INFO[0000] Starting HTTP server on :9180                 source="main.go:72"

```
also two levels
```bash
# cat clouds.yaml 
clouds:
  default:
    auth:
      username: xxx
      ...
  verify: False
# docker run -v /opt/os_exporter/:/etc/openstack/ -it quay.io/niedbalski/openstack-exporter-linux-amd64:master default
INFO[0000] Starting openstack exporter version (version=, branch=, revision=) for cloud: default  source="main.go:38"
INFO[0000] Build context (go=go1.11.13, user=, date=)    source="main.go:39"
ERRO[0000] enabling exporter for service network failed: unable to load clouds.yaml: failed to unmarshal yaml: yaml: unmarshal errors:
  line 8: cannot unmarshal !!bool `False` into clientconfig.Cloud  source="main.go:51"
ERRO[0000] enabling exporter for service compute failed: unable to load clouds.yaml: failed to unmarshal yaml: yaml: unmarshal errors:
  line 8: cannot unmarshal !!bool `False` into clientconfig.Cloud  source="main.go:51"
ERRO[0000] enabling exporter for service image failed: unable to load clouds.yaml: failed to unmarshal yaml: yaml: unmarshal errors:
  line 8: cannot unmarshal !!bool `False` into clientconfig.Cloud  source="main.go:51"
ERRO[0000] enabling exporter for service volume failed: unable to load clouds.yaml: failed to unmarshal yaml: yaml: unmarshal errors:
  line 8: cannot unmarshal !!bool `False` into clientconfig.Cloud  source="main.go:51"
ERRO[0000] enabling exporter for service identity failed: unable to load clouds.yaml: failed to unmarshal yaml: yaml: unmarshal errors:
  line 8: cannot unmarshal !!bool `False` into clientconfig.Cloud  source="main.go:51"
INFO[0000] Starting HTTP server on :9180                 source="main.go:72"
```
but it is still not working.

**Comment by kiblik** [comment]
BTW I tried to use also `cacert`. It is not working also.

**Comment by niedbalski** [comment]
@kiblik 

You should see this log entry https://github.com/openstack-exporter/openstack-exporter/blob/master/exporters/exporter.go#L131 

I don't think you are running the latest docker image (maybe need to refresh?)

**Comment by kiblik** [comment]
I'm sure that image is up-to-date
```bash
# docker pull quay.io/niedbalski/openstack-exporter-linux-amd64:master
master: Pulling from niedbalski/openstack-exporter-linux-amd64
[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the quay.io registry NOW to avoid future disruption.
8e674ad76dce: Already exists 
e77d2419d1c2: Already exists 
5c8199c1140e: Already exists 
Digest: sha256:b05a68dd8679617b8bf23d3229f805cea53776132b5ac7302a673e449fb2889f
Status: Image is up to date for quay.io/niedbalski/openstack-exporter-linux-amd64:master
quay.io/niedbalski/openstack-exporter-linux-amd64:master
# docker run -v /opt/os_exporter/:/etc/openstack/ -it quay.io/niedbalski/openstack-exporter-linux-amd64:master default
INFO[0000] Starting openstack exporter version (version=, branch=, revision=) for cloud: default  source="main.go:38"
INFO[0000] Build context (go=go1.11.13, user=, date=)    source="main.go:39"
ERRO[0000] enabling exporter for service network failed: Post https://XXX:5000/v2.0/tokens: x509: certificate signed by unknown authority  source="main.go:51"
ERRO[0000] enabling exporter for service compute failed: Post https://XXX:5000/v2.0/tokens: x509: certificate signed by unknown authority  source="main.go:51"
ERRO[0000] enabling exporter for service image failed: Post https://XXX:5000/v2.0/tokens: x509: certificate signed by unknown authority  source="main.go:51"
ERRO[0000] enabling exporter for service volume failed: Post https://XXX:5000/v2.0/tokens: x509: certificate signed by unknown authority  source="main.go:51"
ERRO[0000] enabling exporter for service identity failed: Post https://XXX:5000/v2.0/tokens: x509: certificate signed by unknown authority  source="main.go:51"
INFO[0000] Starting HTTP server on :9180                 source="main.go:72"
```

**Comment by niedbalski** [comment]
@kiblik gotcha, I think you are right. This needs to be fixed on gophercloud, I've opened
an issue and will likely provide a PR for fixing this https://github.com/gophercloud/gophercloud/issues/1726

**Comment by niedbalski** [comment]
@kiblik I've merge PR #36 , please check the latest master images and let me know the results.

**Comment by kiblik** [comment]
It works. Thanks
```
...
INFO[0000] SSL verification disabled on transport        source="exporter.go:127"
...
```
